PUT http://localhost:3000/equipo/1 HTTP/1.1
Content-Type: application/json

{
    "Nombre": "galko",
    "Descripcion": "casimiro buenvizco",
    "Serial": "RR23RR"
}

####
DELETE http://localhost:3000/equipo/1 HTTP/1.1

####
POST http://localhost:3000/equipo HTTP/1.1
Content-Type: application/json

{
    "Nombre": "BRASIL",
    "Descripción": "campeon",
    "Serial": "CJRBXD",
    "FechaInicialMarcha": "2000-11-13",
    "UltimaPuestaMarcha": "2006-05-22",
    "UltimoMantenimiento": "2008-03-05",
    "id": 4
}