PUT http://localhost:3000/trabajo/2 HTTP/1.1
Content-Type: application/json

{
    "Estatus": "Hacer",
    "FechaInicio": "2023-01-01"
}

####
DELETE http://localhost:3000/trabajo/2 HTTP/1.1

####
POST http://localhost:3000/trabajo HTTP/1.1
Content-Type: application/json

{  
    "id": 5,
    "FechaPlanificada":"2007-12-01",
    "FechaInicio":"2010-02-22",
    "FechaFinal":"2010-03-26",
    "Estatus":"Hacer",
    "id_Equipo" : 2
}